
import React from 'react';
import {
  AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, ReferenceLine,
  Radar, RadarChart, PolarGrid, PolarAngleAxis, PolarRadiusAxis
} from 'recharts';
import { VocalAnalysis } from '../types';

interface Props {
  data: VocalAnalysis;
}

const AnalysisDashboard: React.FC<Props> = ({ data }) => {
  const isCoreOnly = data?.groundingSources?.some(s => s.title.includes('Archival Knowledge'));
  const pitchData = data?.technicalDiagnostics?.pitchMovement || [];

  const radarData = [
    { subject: 'Luminous', A: data?.timbre?.radarMetrics?.luminous ?? 50, fullMark: 100 },
    { subject: 'Ethereal', A: data?.timbre?.radarMetrics?.ethereal ?? 50, fullMark: 100 },
    { subject: 'Metallic', A: data?.timbre?.radarMetrics?.metallic ?? 50, fullMark: 100 },
    { subject: 'Profound', A: data?.timbre?.radarMetrics?.profound ?? 50, fullMark: 100 },
    { subject: 'Compressed', A: data?.timbre?.radarMetrics?.compressed ?? 50, fullMark: 100 },
  ];

  const handleExport = () => {
    if (!data) return;
    const report = `
VOCALPRINT AI - ARCHIVAL MANUSCRIPT
====================================
Subject: ${data.artistName || 'N/A'}
Classification: ${data.vocalRange?.classification || 'N/A'}
Ambitus: ${data.vocalRange?.low || 'N/A'} - ${data.vocalRange?.high || 'N/A'}

EXPERT VERDICT & COMPARISON:
---------------------------
${data.expertVerdict || 'N/A'}

TIMBRAL PROFILE:
----------------
Description: ${data.timbre?.description || 'N/A'}
Characteristics: ${data?.timbre?.characteristics?.join(', ') || 'N/A'}

TECHNICAL DIAGNOSTICS:
----------------------
Pitch Stability: ${data.technicalDiagnostics?.pitchStability ?? 0}%
Vibrato Intensity: ${data.technicalDiagnostics?.vibrato?.intensity ?? 0}%
Noise Texture: ${data.technicalDiagnostics?.noiseTexture?.amount ?? 0}%

${!isCoreOnly ? `SEMANTIC TIMELINE:
------------------
${data?.vocalSemanticMapping?.map(m => `[${m.timestamp}] ${m.section}: "${m.lyricSnippet}" -> Techniques: ${m.tags?.join(', ')}`).join('\n') || 'N/A'}` : ''}
---
Generated by VocalPrint AI // Anno MMXXV
`;
    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `VocalPrint_Manuscript_${(data.artistName || 'Artist').replace(/\s+/g, '_')}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const getSectionColor = (section: string) => {
    const s = (section || '').toLowerCase();
    if (s.includes('chorus') && !s.includes('pre')) return 'text-pink-500 border-pink-500 bg-pink-500/10 shadow-[0_0_15px_rgba(255,45,117,0.2)]';
    if (s.includes('pre-chorus') || s.includes('предприпев')) return 'text-amber-500 border-amber-500 bg-amber-500/10 shadow-[0_0_15px_rgba(245,158,11,0.2)]';
    if (s.includes('verse') || s.includes('куплет')) return 'text-emerald-500 border-emerald-500 bg-emerald-500/10 shadow-[0_0_15px_rgba(16,185,129,0.2)]';
    return 'text-sky-400 border-sky-400 bg-sky-400/10 shadow-[0_0_15px_rgba(56,189,248,0.2)]';
  };

  return (
    <div className="space-y-32 animate-in fade-in slide-in-from-bottom-6 duration-1000">
      {/* HEADER SECTION */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-end border-b border-pink-500/10 pb-12 relative">
        <div className="absolute top-0 left-0 w-16 h-1 border-t-2 border-l-2 border-pink-500/30"></div>
        <div className="space-y-4">
          <div className="flex items-center gap-4 mb-4">
            <span className="text-pink-500/40 text-[10px] font-black uppercase tracking-[0.8em] block">Neural Vocal Manuscript</span>
            {data?.groundingSources?.some(s => s.title.includes('Librosa')) ? (
              <div className="flex items-center gap-2 px-3 py-1 bg-emerald-500/10 border border-emerald-500/20 text-emerald-500 text-[8px] font-black uppercase tracking-widest animate-pulse">
                <div className="w-1.5 h-1.5 rounded-full bg-emerald-500 shadow-[0_0_8px_#10b981]"></div>
                Librosa Spectral Engine Active
              </div>
            ) : (
              <div className="flex items-center gap-2 px-3 py-1 bg-amber-500/10 border border-amber-500/20 text-amber-500 text-[8px] font-black uppercase tracking-widest">
                <div className="w-1.5 h-1.5 rounded-full bg-amber-500"></div>
                Archival Knowledge Mode
              </div>
            )}
          </div>
          <h1 className="text-7xl md:text-9xl font-serif italic text-white mb-4 tracking-tighter leading-none">{data?.artistName || 'Unknown Subject'}</h1>
          <div className="flex gap-6 items-center">
            <span className="px-6 py-2 bg-pink-600 text-black text-[10px] font-baroque font-black uppercase tracking-widest shadow-[0_0_30px_rgba(255,45,117,0.3)]">
              {data?.vocalRange?.classification || 'Processing'}
            </span>
            <span className="text-pink-100/30 text-lg font-serif italic tracking-tighter">
              Ambitus: {data?.vocalRange?.low ?? 'N/A'} — {data?.vocalRange?.high ?? 'N/A'}
            </span>
          </div>
        </div>
        <div className="mt-12 md:mt-0 flex flex-col items-center md:items-end gap-6">
          <div className="flex flex-col sm:flex-row gap-4">
            <button
              onClick={handleExport}
              className="px-8 py-4 bg-[#ff2d75]/10 border border-[#ff2d75]/40 text-[#ff2d75] font-baroque font-black text-[10px] uppercase tracking-[0.3em] hover:bg-[#ff2d75] hover:text-black transition-all shadow-lg flex items-center gap-4 group"
            >
              <svg className="w-4 h-4 group-hover:scale-110 transition-transform" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" /></svg>
              Export Manuscript (.txt)
            </button>
            <button
              onClick={() => {
                const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
                const url = URL.createObjectURL(blob);
                const link = document.createElement('a');
                link.href = url;
                link.download = `VocalPrint_RawData_${(data.artistName || 'Artist').replace(/\s+/g, '_')}.json`;
                document.body.appendChild(link);
                link.click();
                document.body.removeChild(link);
                URL.revokeObjectURL(url);
              }}
              className="px-8 py-4 bg-pink-500 text-black font-baroque font-black text-[10px] uppercase tracking-[0.3em] hover:bg-white transition-all shadow-[0_0_30_rgba(255,45,117,0.4)] flex items-center gap-4 group"
            >
              <svg className="w-4 h-4 group-hover:scale-110 transition-transform" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a2 2 0 002 2h12a2 2 0 002-2v-1m-4-4l-4 4m0 0l-4-4m4 4V4" /></svg>
              Download Neural JSON
            </button>
          </div>
        </div>
      </div>

      {/* TEXTUAL SUMMARY & COMPARATIVE METRICS */}
      <div className="grid grid-cols-1 lg:grid-cols-5 gap-16">
        <div className="lg:col-span-3 space-y-12">
          <div className="flex items-center gap-4">
            <h2 className="text-[12px] font-black uppercase tracking-[1em] text-pink-500/60">Expert Verdict & Comparative Review</h2>
            <div className="h-px flex-1 bg-pink-500/10"></div>
          </div>
          <div className="space-y-12">
            {(() => {
              const verdict = data?.expertVerdict || 'Archival manuscript is being generated...';
              // More robust splitting: handles "Section Name:", "### Section Name", and ignores case
              const sections = verdict.split(/(?=(?:###\s*)?(?:TIMBRAL PROFILE|TECHNICAL DIAGNOSTICS|SEMANTIC TIMELINE)[:\s]*?$|(?:\n(?:###\s*)?(?:TIMBRAL PROFILE|TECHNICAL DIAGNOSTICS|SEMANTIC TIMELINE)[:\s]*?$))/gm);

              if (sections.length <= 1 && !verdict.match(/(TIMBRAL PROFILE|TECHNICAL DIAGNOSTICS|SEMANTIC TIMELINE)/i)) {
                return (
                  <div className="baroque-panel p-10 md:p-16 relative">
                    <div className="absolute -top-4 -left-4 w-12 h-12 border-t-2 border-l-2 border-pink-500/30"></div>
                    <div className="text-2xl md:text-3xl font-serif italic text-pink-50/90 leading-relaxed whitespace-pre-wrap">
                      {verdict}
                    </div>
                  </div>
                );
              }

              return sections.map((section, idx) => {
                const titleMatch = section.match(/(?:###\s*)?(TIMBRAL PROFILE|TECHNICAL DIAGNOSTICS|SEMANTIC TIMELINE)[:\s]*/i);
                const title = titleMatch ? titleMatch[1].toUpperCase() : '';
                const content = section.replace(/(?:###\s*)?(TIMBRAL PROFILE|TECHNICAL DIAGNOSTICS|SEMANTIC TIMELINE)[:\s]*/i, '').trim();

                if (!title && !content) return null;

                return (
                  <div key={idx} className="baroque-panel p-8 md:p-12 relative group hover:border-pink-500/40 transition-all">
                    <div className="absolute -top-2 -left-2 w-6 h-6 border-t border-l border-pink-500/50"></div>
                    {title && (
                      <h3 className="text-[10px] font-black font-baroque text-pink-500 uppercase tracking-[0.4em] mb-6 border-b border-pink-500/10 pb-4 inline-block">
                        {title}
                      </h3>
                    )}
                    <div className="text-xl md:text-2xl font-serif italic text-pink-50/80 leading-relaxed whitespace-pre-wrap">
                      {content || section}
                    </div>
                  </div>
                );
              });
            })()}
          </div>

          {/* COMPARISON SUB-SECTION */}
          {data?.comparison && (
            <div className="p-10 border border-pink-500/20 bg-pink-500/5 space-y-6">
              <div className="flex items-center gap-3">
                <span className="text-[10px] font-black uppercase tracking-[0.6em] text-pink-500">Benchmark Comparison: {data.comparison.referenceName}</span>
                <div className="px-2 py-0.5 bg-pink-500 text-black text-[8px] font-black">{data.comparison.overallMatch}% Match</div>
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-10">
                <div className="space-y-4">
                  <span className="text-[9px] font-black uppercase text-emerald-500 tracking-widest">Similarities</span>
                  <ul className="list-disc list-inside text-xs text-pink-100/60 font-serif italic space-y-2">
                    {data.comparison.similarities?.map((s, i) => <li key={i}>{s}</li>)}
                  </ul>
                </div>
                <div className="space-y-4">
                  <span className="text-[9px] font-black uppercase text-rose-500 tracking-widest">Technical Deltas</span>
                  <ul className="list-disc list-inside text-xs text-pink-100/60 font-serif italic space-y-2">
                    {data.comparison.differences?.map((d, i) => <li key={i}>{d}</li>)}
                  </ul>
                </div>
              </div>
            </div>
          )}

          {/* SPECTRAL METRICS (Hidden in Core Mode) */}
          {!isCoreOnly && (
            <>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                <div className="p-8 border border-emerald-500/20 bg-emerald-500/5 relative overflow-hidden group">
                  <div className="absolute top-0 right-0 w-24 h-24 bg-emerald-500/5 -translate-y-1/2 translate-x-1/2 rounded-full blur-2xl"></div>
                  <span className="text-[9px] font-black uppercase tracking-widest text-emerald-400 mb-2 block">Breath Control Index (Verse)</span>
                  <p className="text-2xl font-serif italic text-white mb-2">{data?.technicalDiagnostics?.breathControl?.status || 'Refined & Balanced'}</p>
                  <div className="w-full h-1 bg-emerald-950/30 mt-4">
                    <div className="h-full bg-emerald-500 transition-all duration-1000" style={{ width: `${data?.technicalDiagnostics?.breathControl?.index ?? 85}%` }}></div>
                  </div>
                </div>
                <div className="p-8 border border-rose-500/20 bg-rose-500/5 relative overflow-hidden group">
                  <div className="absolute top-0 right-0 w-24 h-24 bg-rose-500/5 -translate-y-1/2 translate-x-1/2 rounded-full blur-2xl"></div>
                  <span className="text-[9px] font-black uppercase tracking-widest text-rose-400 mb-2 block">Compression Friction (Chorus)</span>
                  <p className="text-2xl font-serif italic text-white mb-2">{data?.technicalDiagnostics?.compressionFriction?.status || 'Technical Constriction'}</p>
                  <div className="w-full h-1 bg-rose-950/30 mt-4">
                    <div className="h-full bg-rose-500 transition-all duration-1000" style={{ width: `${data?.technicalDiagnostics?.compressionFriction?.index ?? 45}%` }}></div>
                  </div>
                </div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                <div className="p-6 border border-sky-500/10 bg-sky-500/5 relative">
                  <span className="text-[8px] font-black uppercase tracking-widest text-sky-400/60 mb-2 block">Pitch Stability</span>
                  <div className="flex items-end gap-2">
                    <span className="text-2xl font-sans font-thin text-white">{data?.technicalDiagnostics?.pitchStability ?? 90}%</span>
                    <span className="text-[9px] text-sky-500/40 mb-1">Crystalline</span>
                  </div>
                  <div className="w-full h-0.5 bg-sky-950/30 mt-3">
                    <div className="h-full bg-sky-500" style={{ width: `${data?.technicalDiagnostics?.pitchStability ?? 90}%` }}></div>
                  </div>
                </div>
                <div className="p-6 border border-purple-500/10 bg-purple-500/5 relative">
                  <span className="text-[8px] font-black uppercase tracking-widest text-purple-400/60 mb-2 block">Vibrato Intensity</span>
                  <div className="flex items-end gap-2">
                    <span className="text-2xl font-sans font-thin text-white">{data?.technicalDiagnostics?.vibrato?.intensity ?? 50}%</span>
                    <span className="text-[9px] text-purple-500/40 mb-1">{data?.technicalDiagnostics?.vibrato?.type || 'Steady'}</span>
                  </div>
                  <div className="w-full h-0.5 bg-purple-950/30 mt-3">
                    <div className="h-full bg-purple-500" style={{ width: `${data?.technicalDiagnostics?.vibrato?.intensity ?? 50}%` }}></div>
                  </div>
                </div>
                <div className="p-6 border border-pink-500/10 bg-pink-500/5 relative">
                  <span className="text-[8px] font-black uppercase tracking-widest text-pink-400/60 mb-2 block">Noise Texture</span>
                  <div className="flex items-end gap-2">
                    <span className="text-2xl font-sans font-thin text-white">{data?.technicalDiagnostics?.noiseTexture?.amount ?? 20}%</span>
                    <span className="text-[9px] text-pink-500/40 mb-1">{data?.technicalDiagnostics?.noiseTexture?.characteristics?.[0] || 'Breathiness'}</span>
                  </div>
                  <div className="w-full h-0.5 bg-pink-950/30 mt-3">
                    <div className="h-full bg-pink-500" style={{ width: `${data?.technicalDiagnostics?.noiseTexture?.amount ?? 20}%` }}></div>
                  </div>
                </div>
              </div>
            </>
          )}

          {/* NEW: 10 CORE CHARACTERISTICS SECTION */}
          <div className="space-y-8">
            <div className="flex items-center gap-4">
              <h2 className="text-[10px] font-black uppercase tracking-[0.8em] text-pink-500/60">Primary Vocal Characteristics (Top 10)</h2>
              <div className="h-px flex-1 bg-pink-500/10"></div>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              {data?.techniques && data.techniques.length > 0 ? (
                data.techniques.slice(0, 10).map((tech, idx) => (
                  <div key={idx} className="p-6 baroque-panel border-pink-500/10 hover:border-pink-500/40 transition-all group">
                    <div className="flex justify-between items-start mb-2">
                      <span className="text-[11px] font-black text-pink-500 uppercase tracking-widest">{tech.name}</span>
                      <span className="text-[9px] text-pink-900 font-black">{tech.prominence}%</span>
                    </div>
                    <p className="text-xs text-pink-100/60 font-serif italic">{tech.description}</p>
                    <div className="w-full h-0.5 bg-pink-900/10 mt-4 overflow-hidden">
                      <div className="h-full bg-pink-500/40 group-hover:bg-pink-500 transition-all duration-1000" style={{ width: `${tech.prominence}%` }}></div>
                    </div>
                  </div>
                ))
              ) : (
                <p className="col-span-full text-center text-pink-500/40 font-serif italic py-10">Спектральные характеристики отсутствуют в данном режиме анализа.</p>
              )}
            </div>
          </div>
        </div>

        <div className="lg:col-span-2 space-y-8">
          {!isCoreOnly && (
            <div className="h-[450px] w-full baroque-panel p-8 bg-black/40 border-pink-900/10 flex flex-col justify-center">
              <span className="text-[9px] font-black text-pink-500/40 uppercase tracking-[0.5em] text-center mb-10">Timbral Spectral Geometry</span>
              <ResponsiveContainer width="100%" height="100%">
                <RadarChart cx="50%" cy="50%" outerRadius="80%" data={radarData}>
                  <PolarGrid stroke="rgba(255,45,117,0.2)" />
                  <PolarAngleAxis dataKey="subject" tick={{ fill: 'rgba(255,231,243,0.8)', fontSize: 11, fontWeight: 900, letterSpacing: '0.1em' }} />
                  <PolarRadiusAxis angle={30} domain={[0, 100]} tick={false} axisLine={false} />
                  <Radar
                    name="Timbre"
                    dataKey="A"
                    stroke="#ff2d75"
                    strokeWidth={2}
                    fill="#ff2d75"
                    fillOpacity={0.3}
                    animationDuration={3000}
                  />
                </RadarChart>
              </ResponsiveContainer>
            </div>
          )}
        </div>
      </div>

      {/* TECHNIQUE LANDSCAPE (TIMELINE MAP) - Hidden in Core Mode */}
      {!isCoreOnly && (
        <div className="space-y-16">
          <div className="flex flex-col md:flex-row md:items-center justify-between gap-8 border-b border-pink-500/10 pb-8">
            <div className="space-y-2">
              <h3 className="text-5xl font-serif italic text-white">Technique <span className="text-pink-600 font-baroque not-italic">Landscape</span></h3>
              <p className="text-[9px] text-pink-900 uppercase font-black tracking-[0.4em]">Temporal Marker Analysis</p>
            </div>
            <div className="flex flex-wrap gap-6">
              <span className="flex items-center gap-3 text-[9px] font-black uppercase tracking-widest text-emerald-500"><div className="w-2.5 h-2.5 rounded-full bg-emerald-500 shadow-[0_0_8px_#10b981]"></div> Verse</span>
              <span className="flex items-center gap-3 text-[9px] font-black uppercase tracking-widest text-amber-500"><div className="w-2.5 h-2.5 rounded-full bg-amber-500 shadow-[0_0_8px_#f59e0b]"></div> Pre-Chorus</span>
              <span className="flex items-center gap-3 text-[9px] font-black uppercase tracking-widest text-pink-500"><div className="w-2.5 h-2.5 rounded-full bg-pink-500 shadow-[0_0_8px_#ff2d75]"></div> Chorus</span>
            </div>
          </div>

          <div className="relative">
            {/* Central Timeline Thread */}
            <div className="absolute left-1/2 top-0 bottom-0 w-px bg-gradient-to-b from-pink-500/50 via-pink-900/10 to-transparent -translate-x-1/2 hidden md:block"></div>

            <div className="space-y-48 pt-10">
              {data?.vocalSemanticMapping?.map((m, i) => {
                const sectionStyle = getSectionColor(m.section);
                const isEven = i % 2 === 0;

                return (
                  <div key={i} className={`flex flex-col md:flex-row gap-16 items-center ${isEven ? 'md:flex-row' : 'md:flex-row-reverse'}`}>
                    {/* Lyric Side */}
                    <div className={`flex-1 w-full space-y-6 ${isEven ? 'md:text-right' : 'md:text-left'}`}>
                      <div className="inline-block">
                        <span className={`px-5 py-2 text-[10px] font-black uppercase tracking-[0.5em] border-2 ${sectionStyle}`}>
                          {m.section}
                        </span>
                      </div>
                      <h4 className="text-4xl md:text-6xl font-serif italic text-pink-50 tracking-tight leading-tight">
                        "{m?.lyricSnippet || 'Snippet N/A'}"
                      </h4>
                      <p className="text-pink-400/50 text-xs font-serif italic tracking-wide max-w-sm ml-auto mr-auto md:ml-auto md:mr-0">
                        {m?.techniqueShift || ''}
                      </p>
                    </div>

                    {/* Timeline Node Hub */}
                    <div className="relative z-10">
                      <div className={`w-28 h-28 rounded-full bg-black border-2 flex items-center justify-center text-sm font-baroque shadow-2xl transition-all hover:scale-110 cursor-help ${sectionStyle.split(' ')[0]} ${sectionStyle.split(' ')[1]}`}>
                        <div className="flex flex-col items-center">
                          <span className="opacity-40 text-[8px] uppercase font-black">Time</span>
                          {m?.timestamp || '0:00'}
                        </div>
                      </div>
                    </div>

                    {/* Technique Tags Side */}
                    <div className={`flex-1 w-full ${isEven ? 'md:text-left' : 'md:text-right'}`}>
                      <div className={`flex flex-wrap gap-4 ${isEven ? 'md:justify-start' : 'md:justify-end'}`}>
                        {m?.tags?.map((tag, ti) => (
                          <div key={ti} className="group relative">
                            <span className="px-6 py-3 bg-black border border-pink-500/20 text-pink-400 font-baroque font-black text-[11px] uppercase tracking-widest hover:border-pink-500 hover:text-white hover:bg-pink-500/10 transition-all cursor-help block shadow-lg">
                              {tag}
                            </span>
                            {/* Tooltip for tag */}
                            <div className="absolute bottom-full left-1/2 -translate-x-1/2 mb-3 w-40 p-4 bg-pink-600 text-black text-[9px] font-black uppercase leading-tight opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none z-20 shadow-2xl">
                              <div className="absolute bottom-[-6px] left-1/2 -translate-x-1/2 w-0 h-0 border-l-[6px] border-l-transparent border-r-[6px] border-r-transparent border-t-[6px] border-t-pink-600"></div>
                              Vocal Marker: {tag} Detected
                            </div>
                          </div>
                        ))}
                      </div>
                      <div className={`mt-6 text-[10px] text-pink-900 uppercase font-black tracking-widest ${isEven ? 'md:text-left' : 'md:text-right'}`}>
                        Emotional Intensity: <span className="text-pink-500">{m?.emotionalIntent || 'Processing'}</span>
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      )}

      {/* FOOTER KNOWLEDGE GROUNDING */}
      <div className="border-t border-pink-950/20 pt-24 text-center pb-32">
        <span className="text-[10px] font-black uppercase tracking-[1em] text-pink-900 block mb-12">Archival Knowledge Bases</span>
        <div className="flex flex-wrap justify-center gap-6">
          {data?.groundingSources?.map((s, i) => (
            <a key={i} href={s.uri} target="_blank" rel="noopener noreferrer" className="px-8 py-5 bg-black border border-pink-900/30 text-[10px] font-black text-pink-700 hover:text-pink-400 hover:border-pink-500 transition-all flex items-center gap-5 group">
              <svg className="w-5 h-5 opacity-40 group-hover:opacity-100 group-hover:scale-110 transition-all" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1} d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" /></svg>
              {s?.title?.toUpperCase() || 'EXTERNAL ARCHIVE'}
            </a>
          ))}
        </div>
      </div>
    </div>
  );
};

export default AnalysisDashboard;
